services:
  - type: web
    name: erosionwatch
    env: python
    plan: free
    pythonVersion: "3.10"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --timeout 60
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "info"
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1